Tutorial, Equations: Basics
Zimmi48/platform-docs pull request #1
Opened 2024-04-29 12:39 UTC by thomas-lamiaux

A tutorial introducing the basics of the package Equations

2024-04-30 09:02 UTC, Vanille-N requested changes
Thanks for the review request @thomas-lamiaux .

Speaking from the position of someone who is familiar with Coq but has never used Equations before, I'm probably quite close to the intended audience for this tutorial.
I don't have the knowledge to evaluate the completeness of this tutorial, but at least it seems pedagogically sound.

2024-04-30 11:46 UTC, thomas-lamiaux commented on Tutorial_Equations_basics.v
> +
good idea, thanks

2024-04-30 11:53 UTC, thomas-lamiaux commented on Tutorial_Equations_basics.v
> +(** This process quickly gets tedious and complicated to do by hand on real life examples,
@Zimmi48 We do not have one yet. We should set one when writing the contribution guidelines.

2024-04-30 12:17 UTC, thomas-lamiaux commented on Tutorial_Equations_basics.v
> +    For instance, with clause enables us to define a particularly concise
It is [with] but for headings

2024-04-30 12:29 UTC, Vanille-N commented on Tutorial_Equations_basics.v
> +      [app nil l'] rather than [map (nil A) l'] as [A] was declared as an
```suggestion
      [app nil l'] rather than [app (nil A) l'] as [A] was declared as an
```

2024-04-30 12:51 UTC, thomas-lamiaux commented on Tutorial_Equations_basics.v
> +Equations filter'' {A} (l : list A) (p : A -> bool) : list A :=
Does the modification look better to you ?

2024-04-30 13:34 UTC, Vanille-N commented on Tutorial_Equations_basics.v
> +Equations filter'' {A} (l : list A) (p : A -> bool) : list A :=
Yes that's exactly what I had in mind.

2024-05-07 16:04 UTC, thomas-lamiaux commented
While writing this tutorial and reviewing with the developers, we have identified a behavior of `funelim` that was not wanted (described below) which should lead to [modification to Equations](https://github.com/mattam82/Coq-Equations/pull/593). Waiting for it to be changed, I'll switch this PR back to draft.

By default, `funelim` destruct the goal following the pattern of the definition but does not do any simplifications similarly to how `Fixpoint` definition works with `induction`.
It is up to the user to call `simp` by hand. It is particularly annoying in the case of with clauses, as it makes a subclause corresponding to the branch of the with appear, and one has to rewrite it by hand, then simplify again to get the good pattern. As an alternative, you can simplify directly by rewriting by the generated equation `Heqcall`. 
While always solvable by hand in a few lines, it is not a wanted behavior as it introduces an asymmetry in dealing with patterns depending on if they have a with clause or not.

It is like that for `Fixpoint` definitions because `simpl` and `cbn` are not always easy to control, so we do not want simplification to be done automatically. In our case, because we are relying on controlled rewriting, this should actually pose no issues to always rewrite directly by `Heqcall`. It actually has several advantages: 
- It makes proof easier and faster, as we only have to rewrite by one specific equations that we already know, and do not have to do proof search among the different equations as done by `simp f1 ... fn`
- It solves the issue of with clauses
- Users get exactly what they want, pattern match + replacement by the good equality without simplifying the rest of the goal

Moreover, the cost to change it is low has `funelim f; simp f` won't break as `simp f` works even it has nothing left to do, and in the case of with clause, it will actually enable to remove (small) superfluous code.

While hanging the behavior, it was further realized that `Heqcall` was not present in contexts for regular pattern because Equations was wrongfully simplifying opaque terms. Hence, leading to the discovery of an actual bug.

2024-05-13 15:33 UTC, Zimmi48 commented
> Waiting for it to be changed, I'll switch this PR back to draft.

I suggest a different approach: merge now with a note about the issue and the workaround in the tutorial, and let users know that this workaround is not needed anymore after version X. When version X has been released and available to the users (as part of a Coq Platform release) for a while, then it will be time to obliterate the mention of this issue (and instead specify that this is the minimum version required to follow this tutorial).

BTW, thank you Neven for the review. I was also planning to do one (from the same point of view of a non-Equation user), but it's difficult for me to find the time. It's good that this tutorial has been reviewed. Merging it now doesn't prevent improving it even more later...

2024-05-13 23:38 UTC, thomas-lamiaux commented
@Zimmi48 That is a reasonable position, and I guess it should be the default one once the documentation will be actually indexed on the version of the Coq platform. 
There is nothing left to do, so I'll merge for now, and we can update the tutorial, once the modifications to Equations are merged..

2024-05-13 23:38 UTC, merged

2024-06-21 19:32 UTC, jfehrle reviewed
A few cursory observations.  I looked here while reading https://github.com/coq/ceps/pull/91.

2024-06-21 19:32 UTC, jfehrle commented on src/Tutorial_Equations_basics.v
> +  well-founded recursion and obligations.
Where can the reader find definitions of "dependent pattern matching", "well-founded recursion" and "obligations"?
I notice the text uses "obligations" only in this sentence.

2024-06-21 19:32 UTC, jfehrle commented on src/Tutorial_Equations_basics.v
> +  tactics, and can automatically derive properties like no-confusion
"no-confusion property" - where is this defined and explained?

2024-06-21 19:32 UTC, jfehrle commented on src/Tutorial_Equations_basics.v
> +  In section 1, we explain how to define basic functions by dependent
"basic functions" or just "functions"?

2024-06-21 19:32 UTC, jfehrle commented on src/Tutorial_Equations_basics.v
> +    rather than using Fixpoint and match.
Why would someone prefer to use Equations instead of Fixpoint?  Would be nice to show a comparative example first using Fixpoint, then using Equations.

2024-06-22 14:25 UTC, thomas-lamiaux commented on src/Tutorial_Equations_basics.v
> +  In section 1, we explain how to define basic functions by dependent
Basic functions, with and where clauses are discussed in respectively section 2 and 3

2024-06-22 14:26 UTC, thomas-lamiaux commented on src/Tutorial_Equations_basics.v
> +    rather than using Fixpoint and match.
We thought about that but we already wanted to have a clear tutorial which was not the case before. Maybe be having a how-to "when to use Equations" could be useful ?

2024-06-22 15:35 UTC, jfehrle commented on src/Tutorial_Equations_basics.v
> +    rather than using Fixpoint and match.
IMO the first paragraph in any tutorial should state the benefit of reading the tutorial and of using the described feature.  Stating the motivation (or goal) makes it much easier to follow/absorb the contents.

2024-06-22 15:53 UTC, thomas-lamiaux commented on src/Tutorial_Equations_basics.v
> +    rather than using Fixpoint and match.
It sounds like a good idea, but some packages like Equations will more than one tutorial. In this case, I think it could be interesting to have a first page like that https://coq.inria.fr/doc/V8.19.0/refman/language/core/index.html

2024-06-22 16:02 UTC, jfehrle commented on src/Tutorial_Equations_basics.v
> +    rather than using Fixpoint and match.
Sure.  That first page should also state the benefit/purpose of the feature.  It doesn't need to be an exhaustive statement.

2024-06-23 20:19 UTC, thomas-lamiaux commented on src/Tutorial_Equations_basics.v
> +    rather than using Fixpoint and match.
Also a good reason to use a first page, is that Equations is to particularly good to well-founded recursion or dependent functional programming, and it can hardly be explained in 5 minutes in the basic tutorials.
As you mentioned, in the intro it currently sounds weird.