Adding a Search tutorial
Zimmi48/platform-docs pull request #11
Opened 2024-05-14 09:24 UTC by Villetaneuse

There are no exercises yet, but this can be for a later version.

2024-05-14 10:43 UTC, MSoegtropIMC requested changes
IMHO the role of scopes should be mentioned immediately when searching for operators is introduced. It is mentioned later, but I think the combination with searching for nat and an operator is misleading. Instead one should instruct to search for `(_ + _)%nat`.

Otherwise a very nice tutorial - I learned a bit :-)

2024-05-14 10:43 UTC, MSoegtropIMC commented on src/SearchTutorial.v
> +Search nat (_ + _) (_ * _). (* still too much *)
This won't work in general. An important point about searching notations is that the interpretation of notations in Search also depends on scoping. Say one could do Search `(_ + _)%Z`. If you open Z scope, a search for `nat` and `(_ + _)` you only get the lemmas which connect nat and Z addition.

2024-05-14 11:15 UTC, thomas-lamiaux approved these changes
That is a very good tutorial, thanks.

2024-05-14 11:15 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +    combines search items in order to be more precise. *)
```suggestion
    combines search items in order to be more precise. 
    For instance, let's search for distributivity of multiplication over addition.  *)
```

2024-05-14 11:15 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +(** Search all lemmas where the type [nat] and the operators (_ * _) and
```suggestion
(** To do so, we can first search for all lemmas where the type [nat] and the operators (_ * _) and
```

2024-05-14 11:15 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +(** In this tutorial, we are going to search for lemmas, mostly about natural
I would add a few more informal explanations about [Search] and what it does, like check in the scope. 
Possibly merging with the summary ?

2024-05-14 11:15 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +    outside a specific [Module] (see the [module tutorial](TODO.todo) for
Should we have explicit todo  ? 
It might be better to leave nothing unattended, and rather come back later to improve it ?

2024-05-14 11:15 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +(** It often happens that we [Search] in the middle of a proof for a lemma we
I suggest adding a running example, as done in section 1.1 and 1.2. 
I think it helps to contextualize and see the power of the feature.
Maybe a lemma about </<= could be a good idea ? 
There often have rich intro / conclusion and are not always easy to find

2024-05-14 11:29 UTC, thomas-lamiaux commented
> There are no exercises yet, but this can be for a later version.

Exercises can definitely be added in future version. Though, if there is no particular rush to merge the PR, I suggest adding a few exercises to section 1 before merging. Exercises for section 2 seems more optional to me as it is a section about more advanced features.

2024-05-14 16:35 UTC, Villetaneuse commented on src/SearchTutorial.v
> +Search nat (_ + _) (_ * _). (* still too much *)
Thank you very much, I will take it into account. This is will be some work, though, to keep it reasonably straightforward for new users.

2024-05-14 16:38 UTC, Villetaneuse commented on src/SearchTutorial.v
> +(** ** Filtering on hypotheses (parameters) or conclusions (return type) *)
Thank you, done.

2024-05-14 16:38 UTC, Villetaneuse commented on src/SearchTutorial.v
> +    combines search items in order to be more precise. *)
done

2024-05-14 16:39 UTC, Villetaneuse commented on src/SearchTutorial.v
> +    outside a specific [Module] (see the [module tutorial](TODO.todo) for
done

2024-05-14 16:44 UTC, Villetaneuse commented
I've taken into account your most easy criticisms. I will get back to it tomorrow, if I have some time, to include your other remarks and @MSoegtropIMC's remark about scopes.

2024-05-15 16:03 UTC, Villetaneuse commented
Here is my latest iteration. I have added exercises and a discussion about scopes. It's not totally finished.

2024-05-15 16:31 UTC, MSoegtropIMC commented on src/SearchTutorial.v
> +Search nat (_ + _) (_ * _). (* still too much *)
I had a look at your update. Very nice - just I am not sure if using sum and product types in beginner examples is the best choice - not everybody knows what `nat + bool` and `nat * bool` mean. I would import ZArith and discuss `(1+2)%nat` vs `(1+2)%Z`. Of course in the commands you issue one would see the type variants ...

2024-05-15 16:59 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +        - 1.1.1 Exercise:
A unnumbbered subsubsection might be better. It would make the toc easier to read.

2024-05-15 17:31 UTC, thomas-lamiaux reviewed
Adding the exercises is great. It true that in your case, we would like to be able to display the solutions. 

Section 1.2 is good, but I feel the storytelling it is a bit rough, the title and the content feels technical to me. 

I would suggest merging section 1.2 and 1.3 in a section "Searching using notations" which sounds more purpose oriented for the reader than "necessary digression". Then I would adopt the slightly different storytelling 
- Oh we would like to search for notations because idk that's what we see in our goals
- Some works fine (ex from 1.3 that are fine), but issues some are overloaded and that is normal
- how to solve the issue => scopes
- diverse examples with scopes

Moreover, merging 1.2 and 1.3 shouldn't be too long either because 1.3 doesn't actually have that much original content now that there is 1.2

2024-05-15 17:31 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +    constants whose name contains "add" _and_ type contains [Nat.mul]. *)
Rough transition ? It is not perfect but what about sth like
```suggestion
(** In practice, we often want to search for lemmas satisfying multiple criteria at one, 
    e.g, search for all lemmas contains "add" in their names _and_ which type contains [Nat.mul].
    We can do so by giving  TODO *)
```

2024-05-15 17:31 UTC, thomas-lamiaux commented on src/SearchTutorial.v
> +    contain "mul": *)
```suggestion
    contain "mul", so we can filter them out to get clearer results by adding [-"mul"] *)
```

2024-05-16 08:43 UTC, Villetaneuse commented
Again an iteration, where I have taken most of your remarks into account except:
- I still don't `Require ZArith.BinInt`, but I have added sentences saying it's not a big deal if one does not know `sum` between types.
- I have not changed the `concl:` part with a narrative
- I have not changed the summary yet
- I have not changed the numering of exercises yet

However, I think we should move on. There can be modifications later and more following users' feedbacks.

2024-05-16 10:59 UTC, merged

2024-05-16 10:59 UTC, thomas-lamiaux commented
Ok, that sounds good enough, but we should be careful not to forget and never come back to it.

2024-05-16 11:06 UTC, Zimmi48 commented
If you want to, you can open issues to track things that need to be taken care of in the future.

2024-05-16 12:07 UTC, Villetaneuse commented
To make my previous thoughts clearer: I am very grateful for your many remarks, but, from my experience, working on pedagogical content is **literally infinite**. We can always make a new version which is better by an epsilon margin. At some point, though, one needs to fix a "good enough" limit (I would rate my own limit as already pretty high). Does this tutorial effectively teaches how to use `Search`? I'd say probably. Most of its defects cannot be foretold at this point and will be revealed by users anyway.

2024-05-16 12:47 UTC, thomas-lamiaux commented
I agree and I think it is a good point. Though, we should be careful to stuffs like sum up and toc as it what users are going to see first and checkout to decide if they will read the tutorial or not